### ISSUE TITLE
Publish to the PowerShell Gallery

### ISSUE THREAD

**Issue by ngetchell** [smurawski/PowerShellGuard#10]
I use this module every day and when I setup a new machine I have to register the AppVeyor nuget feed to get the latest bits.

**Comment by usepowershell** [comment]
Will do

**Comment by jpvantuyl** [comment]
This can be closed.  PowerShell guard is in the gallery.

https://www.powershellgallery.com/packages/PowerShellGuard/

**Comment by ngetchell** [comment]
But the latest on the Gallery is 0.6.1 while the repo has 0.8.0.

**Comment by jpvantuyl** [comment]
Good point.  The latest is greatest.

**Comment by usepowershell** [comment]
@ngetchell and @jpvantuyl  I pulshed 0.8.0 to the Gallery last week.  Better CI/CD coming soon.
