### ISSUE TITLE
What is 'Guard'?

### ISSUE THREAD

**Issue by 1RedOne** [smurawski/PowerShellGuard#11]
The readme references Guard but doesn't give a newcomer any idea of what Guard is, or even what company makes it.  Maybe add a link to the wiki page of Guard, or a link to the Guard company's product site?

Of course, we can't rule out the very real possibility that everyone else in the world knows about Guard, except me.

**Comment by 1RedOne** [comment]
Submitted GH-12 here answering my own question. https://github.com/smurawski/PowerShellGuard/pull/12

**Comment by usepowershell** [comment]
Merged.  Thanks!
