### ISSUE TITLE
The "=" operator is missing after a named argument.

### ISSUE THREAD

**Issue by craibuc** [smurawski/PowerShellGuard#4]
Error generated when attempting to Import-Module:

> The "=" operator is missing after a named argument.
> At C:\Users\cb2215\Documents\WindowsPowerShell\Modules\PowerShellGuard\PowerShellGuard.psm1:23 char:50
> -       [parameter(ValueFromPipelineByPropertyName) <<<< ]
>   - CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>   - FullyQualifiedErrorId : MissingEqualsInNamedArgument

```
PS> $PSVersionTable.PSVersion

  Major  Minor  Build  Revision
  -----  -----  -----  --------
  2      0      -1     -1
```

**Comment by usepowershell** [comment]
@craibuc As of PowerShell 3, you no longer need to specify "= $true" for parameters.  I actually just added a module manifest that sets the minimum version for the module to PS3.  I really didn't plan to support PowerShell v2 with this module.  V2 the only way you can use it?

**Comment by craibuc** [comment]
I'm using v2.  At this point, I'm not able to move to v3.  Is there a reason why you can't support v2?

**Comment by usepowershell** [comment]
Honestly, I don't use v2 unless I'm testing something and didn't want to spend cycles on verifying compatibility given v2 is a different clr.

I did merge your changes and if it works with those for you that's awesome. There was a merge conflict so I had to do it manually.
